"""Prompt templates for Claude API web app generation."""

import random
from datetime import date
from fetchers.base_fetcher import Anniversary
from config import Language


# App style variations for creative diversity
APP_STYLES = [
    "retro pixel art aesthetic with vibrant colors and nostalgic gaming vibes",
    "modern minimalist design with clean typography and bold color accents",
    "newspaper-style layout with vintage typewriter fonts and authentic period feel",
    "interactive museum exhibit with elegant presentation and gallery-like atmosphere",
    "animated infographic with dynamic data visualization and smooth transitions",
    "cinematic storytelling with dramatic visuals and movie-like experience",
    "playful and colorful design with whimsical animations and delightful interactions",
    "elegant timeline with rich historical imagery and immersive scrolling",
    "cyberpunk futuristic style with neon colors and glitch effects",
    "hand-drawn sketch aesthetic with artistic illustrations and organic feel",
    "magazine editorial layout with beautiful photography and grid system",
    "interactive comic book style with speech bubbles and panel transitions",
]


WEBAPP_GENERATION_PROMPT = """You are a creative web developer tasked with creating an engaging, interactive web application to commemorate a historical anniversary.

# Anniversary Details
- **Event**: {title}
- **Date**: {date_formatted}
- **Years Ago**: {years_ago} years
- **Description**: {description}
- **Category**: {category}

# Your Mission: Create Something MEMORABLE

Build a web experience that makes people say "Wow, I never knew that!" or "This is amazing!"

Your app should be:

1. **FASCINATING** - Reveal surprising facts, hidden stories, or unexpected connections
2. **IMMERSIVE** - Transport users to that moment in history through vivid storytelling
3. **INTERACTIVE** - One brilliant interactive element that makes the story come alive:
   - Timeline with clickable events and smooth animations
   - Quiz that teaches while entertaining with clever questions
   - Interactive comparison (then vs now, before/after)
   - Animated story that unfolds as user scrolls
   - Mini-game or simulation related to the event
4. **BEAUTIFUL** - Stunning visuals that match the era and mood of the event
5. **PERSONAL** - Tell stories of real people, their struggles, triumphs, and emotions
6. **COMPACT** - Stay under 6000 tokens - every word must earn its place

Think: "This should feel like a mini-documentary meets an interactive magazine article"

# Technical Requirements

## File Structure
Generate exactly 3 files:

### 1. index.html
- Semantic HTML5 structure
- Include metadata: title, description, viewport, Open Graph tags
- Link to style.css and app.js
- Accessible (proper ARIA labels, alt text, semantic tags)
- Mobile-responsive viewport meta tag
- **Navigation Requirements**:
  * MUST include a link back to the main index page at the top or in header
  * Use relative path: `../../index.html`
  * Link text: "← Back to All Apps" or similar
  * Style it clearly visible but not obtrusive
- **Footer Requirements**:
  * DO NOT include copyright (©) for fictional organizations
  * MUST include: "Generated by AI (Claude) for educational purposes"
  * Example: "<p>Generated by AI (Claude) for educational purposes. All content is for informational use only.</p>"

### 2. style.css
- Modern CSS using flexbox/grid
- Responsive design (mobile-first with media queries)
- Smooth animations and transitions
- Professional color palette appropriate for the event
- Support for both light and dark themes (use prefers-color-scheme)
- Typography: use system fonts for best performance

### 3. app.js
- Pure vanilla JavaScript (no frameworks)
- ONE interactive feature - pick the best fit:
  * Simple timeline with click events (best for historical events)
  * Basic quiz (3-4 questions max, good for testing knowledge)
  * Facts carousel (5-7 facts, simple prev/next buttons)
- Keep it minimal and focused (aim for <150 lines)
- Essential error handling only
- Brief comments on key functions

# Creative Storytelling Framework

## Find the Human Story
Every historical event has people at its center. Ask yourself:
- Who was there? What did they feel, fear, hope?
- What was at stake? What could have gone wrong?
- What surprises or plot twists unfolded?
- How did ordinary people become extraordinary?

## Create Emotional Connection
- **Triumph**: Moments of breakthrough, victory, achievement
- **Tragedy**: Loss, failure, lessons learned the hard way
- **Transformation**: How this moment changed everything
- **Wonder**: The "How did they even do that?" factor
- **Mystery**: Unanswered questions or fascinating details

## Design for "Aha!" Moments
Include at least 2-3 surprising elements:
- Counter-intuitive facts ("You won't believe this...")
- Hidden connections to modern life
- Dramatic comparisons (scale, speed, cost, impact)
- Lesser-known details that change the story
- "What if" scenarios - what almost happened?

## Interactive Storytelling Ideas
Pick ONE that best fits your story:

**Timeline Journey**: Navigate through events with reveals and details
**Then/Now Slider**: Interactive comparison showing change over time
**Decision Points**: "What would you do?" moments with historical context
**Myth Buster**: Quiz that challenges common misconceptions
**Impact Ripples**: Show cascading effects of the event
**Character Perspectives**: Toggle between different viewpoints
**Scale Visualizer**: Make huge numbers/distances comprehensible

# Important Constraints

**CRITICAL**: You MUST follow these rules:

1. **No External Resources**:
   - No CDN links (no jQuery, Bootstrap, Font Awesome, etc.)
   - No external scripts or stylesheets
   - No external images (use CSS gradients, shapes, or inline SVG)
   - No icon fonts (use Unicode characters or CSS shapes)
   - No web fonts (use system font stack)

2. **File Size** - KEEP APPS COMPACT:
   - HTML: < 15KB (aim for 8-12KB)
   - CSS: < 10KB (aim for 5-8KB)
   - JS: < 15KB (aim for 8-12KB)
   - Total output must fit in ~6000 tokens
   - Prioritize quality over quantity - simple and elegant wins
   - Keep it lean and focused

3. **Compatibility**:
   - Must work in modern browsers (Chrome, Firefox, Safari, Edge)
   - No build process needed
   - Works immediately when opening index.html

4. **Best Practices**:
   - Semantic HTML
   - Accessible (keyboard navigation, screen reader friendly)
   - Fast loading (optimize everything)
   - Mobile-first responsive design

5. **Legal & Ethical Requirements**:
   - DO NOT create fictional copyright statements (no "© 2025 XYZ Organization")
   - MUST clearly state content is AI-generated for educational purposes
   - Include disclaimer in footer about informational use only
   - No attribution to non-existent entities

# Style Preference

For this app, consider using: **{style_preference}**

Feel free to interpret this creatively while ensuring the app is professional and engaging.

# Output Format

Return your response in this EXACT format (critical for parsing):

<html_file>
<!DOCTYPE html>
<html lang="en">
<!-- Your complete HTML here -->
</html>
</html_file>

<css_file>
/* Your complete CSS here */
</css_file>

<js_file>
// Your complete JavaScript here
</js_file>

<metadata>
{{
  "app_title": "Brief, catchy title for this app (max 60 chars)",
  "description": "One sentence description of what the app does",
  "tags": ["tag1", "tag2", "tag3"],
  "estimated_engagement": "2-5 minutes"
}}
</metadata>

# Examples of Good Interactive Features

## Timeline Example:
```javascript
const events = [
  {{ year: 1800, text: "Event description" }},
  {{ year: 1850, text: "Another event" }},
  // ...
];
// Create interactive timeline with click/hover
```

## Quiz Example:
```javascript
const questions = [
  {{
    question: "What year did this happen?",
    options: ["1950", "1960", "1970", "1980"],
    correct: 1
  }}
];
// Interactive quiz with score tracking
```

## Facts Carousel Example:
```javascript
const facts = [
  "Interesting fact #1",
  "Interesting fact #2",
  "Interesting fact #3"
];
// Carousel with next/prev buttons
```

# Final Checklist

Before submitting, ensure:
- [ ] All 3 files are complete and well-formatted
- [ ] No external dependencies
- [ ] At least 2 interactive features
- [ ] Responsive design (test at 320px, 768px, 1024px+ widths)
- [ ] Accessible (keyboard navigation works, proper ARIA)
- [ ] Engaging and educational content
- [ ] Professional appearance
- [ ] Smooth animations
- [ ] Works in all modern browsers

Now create an amazing web app that brings this anniversary to life!
"""


def build_prompt(anniversary: Anniversary, language: Language = Language.ENGLISH, style_preference: str = None) -> str:
    """Build complete prompt with anniversary data.

    Args:
        anniversary: The anniversary to generate an app for
        language: Target language for the web app
        style_preference: Optional style direction (random if not specified)

    Returns:
        Complete prompt string
    """
    if style_preference is None:
        style_preference = random.choice(APP_STYLES)

    years_ago = date.today().year - anniversary.year

    if language == Language.JAPANESE:
        date_formatted = anniversary.date.strftime("%Y年%m月%d日")
        prompt_template = _get_japanese_prompt_template()
    else:
        date_formatted = anniversary.date.strftime("%B %d, %Y")
        prompt_template = WEBAPP_GENERATION_PROMPT

    prompt = prompt_template.format(
        title=anniversary.title,
        date_formatted=date_formatted,
        years_ago=years_ago,
        description=anniversary.description,
        category=anniversary.category,
        style_preference=style_preference
    )

    return prompt


def _get_japanese_prompt_template() -> str:
    """Get Japanese prompt template."""
    return """あなたは創造的なウェブ開発者です。歴史的な記念日を記念する魅力的でインタラクティブなWebアプリケーションを作成してください。

# 記念日の詳細
- **出来事**: {title}
- **日付**: {date_formatted}
- **経過年数**: {years_ago}年
- **説明**: {description}
- **カテゴリ**: {category}

# あなたのミッション：心に残る体験を創る

「えっ、知らなかった！」「これすごい！」と言わせるWebアプリを作ってください。

あなたのアプリは：

1. **魅力的** - 驚きの事実、隠された物語、意外なつながりを明らかに
2. **没入感** - 生き生きとした語りで、その時代にユーザーを引き込む
3. **インタラクティブ** - 物語を輝かせる1つの優れたインタラクション：
   - クリック可能なイベントとスムーズなアニメーションのタイムライン
   - 学びながら楽しめる賢いクイズ
   - 過去と現在の比較インタラクション
   - スクロールで展開するアニメーションストーリー
   - イベントに関連したミニゲームやシミュレーション
4. **美しい** - 時代と雰囲気にマッチした印象的なビジュアル
5. **人間的** - 実在の人物、彼らの苦悩、勝利、感情を語る
6. **コンパクト** - 6000トークン以内 - すべての言葉に意味を持たせる

目指すもの：「ミニドキュメンタリーとインタラクティブ雑誌記事の融合」

# 技術要件

## ファイル構成
正確に3つのファイルを生成：

### 1. index.html
- セマンティックHTML5構造
- メタデータ含む：title、description、viewport、Open Graphタグ
- style.cssとapp.jsをリンク
- アクセシブル（適切なARIAラベル、alt属性、セマンティックタグ）
- **重要：すべてのテキストを日本語で記述**
- **ナビゲーション要件**:
  * ページ上部またはヘッダーにメインインデックスページへのリンクを必ず含める
  * 相対パス使用: `../../index.html`
  * リンクテキスト: 「← 全アプリ一覧に戻る」または類似の表現
  * 明確に見えるが、邪魔にならないスタイル
- **フッター要件**:
  * 架空の組織の著作権表記（©）は含めない
  * 必須：「このコンテンツはAI（Claude）によって教育目的で生成されました」
  * 例：「<p>このコンテンツはAI（Claude）によって教育目的で生成されました。すべての情報は参考目的のみです。</p>」

### 2. style.css
- モダンなCSS（flexbox/grid）
- レスポンシブデザイン（モバイルファースト、メディアクエリ使用）
- スムーズなアニメーションとトランジション
- プロフェッショナルな配色
- ライト/ダークモード対応（prefers-color-scheme）

### 3. app.js
- Pure vanilla JavaScript（フレームワーク不使用）
- 1つのインタラクティブ機能 - 最適なものを選択：
  * シンプルなタイムライン（歴史的イベントに最適）
  * 基本的なクイズ（3-4問、知識テストに適）
  * 事実カルーセル（5-7つの事実、前/次ボタン）
- **重要：UIテキストとメッセージはすべて日本語で**
- 最小限で焦点を絞って（150行以下を目標）
- 必要最小限のエラーハンドリング
- 主要関数に簡潔なコメント（日本語）

# クリエイティブ・ストーリーテリングの指針

## 人間のドラマを見つける
すべての歴史的出来事の中心には人がいます：
- その場にいたのは誰？何を感じ、恐れ、希望したか？
- 何が賭けられていた？何が間違う可能性があった？
- どんな驚きや展開があった？
- 普通の人々はどのように非凡な存在になったか？

## 感情的つながりを創る
- **勝利**: 突破、勝利、達成の瞬間
- **悲劇**: 喪失、失敗、困難から学んだ教訓
- **変革**: この瞬間がすべてを変えた
- **驚異**: 「どうやってそんなことを？」という要素
- **謎**: 未解決の疑問や魅力的な詳細

## 「なるほど！」の瞬間をデザイン
少なくとも2-3の驚き要素を含める：
- 直感に反する事実
- 現代生活との隠れたつながり
- 劇的な比較（規模、速度、コスト、影響）
- 物語を変える知られざる詳細
- 「もしも」のシナリオ - 起こりえたこと

## インタラクティブストーリーテリングのアイデア
物語に最も合うものを1つ選ぶ：

**時系列の旅**: 詳細が明らかになっていくイベントナビゲーション
**過去/現在スライダー**: 時代の変化を示すインタラクティブ比較
**決断ポイント**: 「あなたならどうする？」歴史的文脈付き
**神話破壊**: よくある誤解に挑戦するクイズ
**影響の波紋**: 出来事の連鎖効果を表示
**人物視点**: 異なる視点を切り替え
**スケール可視化**: 巨大な数字や距離を理解可能に

# 重要な制約

**必須**: 以下のルールを守ること：

1. **外部リソース禁止**:
   - CDNリンク禁止
   - 外部スクリプトやスタイルシート禁止
   - 外部画像禁止（CSS、SVGを使用）
   - Unicodeまたは CSS図形を使用（アイコンフォント禁止）

2. **ファイルサイズ** - コンパクトに：
   - HTML: < 15KB （8-12KBを目標）
   - CSS: < 10KB （5-8KBを目標）
   - JS: < 15KB （8-12KBを目標）
   - 合計出力は約6000トークン以内
   - 量より質 - シンプルで洗練されたものを
   - 焦点を絞って軽量に

3. **互換性**:
   - モダンブラウザで動作
   - ビルドプロセス不要
   - index.htmlを開くだけで動作

4. **言語**:
   - **すべてのコンテンツを日本語で記述**
   - UIテキスト、メッセージ、コメントすべて日本語

5. **法的・倫理的要件**:
   - 架空の組織の著作権表記を作成しない（「© 2025 XYZ組織」など禁止）
   - AI生成コンテンツであることを必ず明記（教育目的）
   - フッターに情報利用に関する免責事項を含める
   - 実在しない団体への帰属表記をしない

# スタイル設定

このアプリには、**{style_preference}** のスタイルを検討してください。

# 出力形式

以下の正確なフォーマットで応答してください：

<html_file>
<!DOCTYPE html>
<html lang="ja">
<!-- 完全なHTMLをここに -->
</html>
</html_file>

<css_file>
/* 完全なCSSをここに */
</css_file>

<js_file>
// 完全なJavaScriptをここに
// UIテキストとメッセージは日本語で
</js_file>

<metadata>
{{
  "app_title": "このアプリの簡潔なタイトル（日本語、最大60文字）",
  "description": "アプリの説明（日本語、1文）",
  "tags": ["タグ1", "タグ2", "タグ3"],
  "estimated_engagement": "2-5分"
}}
</metadata>

この記念日を生き生きと表現する素晴らしいWebアプリを作成してください！
"""
